#!/bin/bash

dl=$1
echo Balancing downlink in $dl

glastAfs=/afs/slac.stanford.edu/g/glast/ground
stage1=${glastAfs}/PipelineStaging
stage2=${glastAfs}/PipelineStaging2

runs=$(ls ${dl} | egrep -o '^r[0-9]+$')

for run in ${runs} ; do
	rd=${dl}/${run}
	
	echo '  ' Balancing run ${run} in ${rd}
	
	for dir in ${stage1}/${run} ${stage2}/${run} ; do
		rm -rf ${dir}
		mkdir -p ${dir}
	done

	even=$(ls ${rd} | egrep -o 'e[0-9]+' | awk '! (NR%2)')

	echo '  ' Even chunks are ${even}

	for chunk in ${even} ; do
		target=${stage2}/${run}/${chunk}
		fake=${stage1}/${run}/${chunk}
		echo '    ' Setting up ${target}
		rm -rf ${target} ${fake}
		mkdir -p ${target}
		ln -sf ${target} ${fake}
	done

done
